name 'formatron_grafana'
version '0.1.1'
description 'Formatron Grafana cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/grafana-cookbook'
issues_url 'https://github.com/formatron/grafana-cookbook/issues'
supports 'ubuntu'
depends 'apt'
depends 'formatron_postgresql'
